edem_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: inspiring-bonus-481514-j4
      threads: 1
      dataset: ecommerce_delivery_gold
      keyfile: credentials.json
      location: europe-west1